# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
   include:
   - release/wasm*
pr:
  branches:
    include:
      - none
      

variables:
  buildConfiguration: 'Release'

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'MelbourneBlazorXamarin.BlazorWasm/MelbourneBlazorXamarin.BlazorWasm.csproj'
    arguments: '--configuration $(buildConfiguration) -o ./publish'
    zipAfterPublish: false

- script: |
    pwd
    ls -R

- task: AzureFileCopy@3
  inputs:
    SourcePath: 'publish/MelbourneBlazorXamarin.BlazorWasm/wwwroot'
    azureSubscription: 'Pay-As-You-Go(951a84dd-fbb0-4ba0-bc31-4865ee7f4df3)'
    Destination: 'AzureBlob'
    storage: 'melbournexamarinblazor'
    ContainerName: '$web'